spring:
  application:
    name: comment

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER_URI}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      repositories:
        enabled: false

  mongodb:
    uri: ${SPRING_MONGODB_URI}
logging:
  level:
    org.mongodb.driver: WARN
    org.mongodb.driver.client: WARN
    org.springframework.data.mongodb: WARN

KEY:
  COMMENT:
    COUNT: ${SPRING_REDIS_KEY_COMMENT_COUNT}
#  RELIES:
#    COUNT: ${SPRING_REDIS_KEY_COMMENT_RELIES_COUNT}

server:
  port: 8085
