spring:
  application:
    name: post

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER_URI}

  datasource:
    password: ${SPRING_MSSQL_PASSWORD}
    username: ${SPRING_MSSQL_USERNAME}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${SPRING_MSSQL_URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 5s

logging:
  level:
    sql: error

server:
  port: 8084


KEY:
  COMMENT:
    COUNT: ${SPRING_REDIS_KEY_COMMENT_COUNT}
  VIEW:
    COUNT: ${SPRING_REDIS_KEY_VIEW_COUNT}