spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authenticate-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
            - id: file-service
              uri:
                http://localhost:8082
              predicates:
                - args:
                    Path=/api/files/**

server:
  port: 8888

