version: "3.9"

services:
  file-service:
    image: file-service:latest
    container_name: file-service
    ports:
      - "8081:8081"
    environment:
      MAIL_USERNAME: hanng1000@gmail.com
      MAIL_PASSWORD: lpll xaad nthr rxkv