spring:
  application:
    name: authenticate
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: {SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

  datasource:
    url: ${SPRING_MYSQL_URI}
    username: ${SPRING_MYSQL_USERNAME}
    password: ${SPRING_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

grpc:
  client:
    profile-service-grpc:
      address: static://localhost:9091
      negotiation-type: plaintext

token:
  secret:
    key: ${TOKEN_SECRET_KEY}

access:
  token:
    expired: 1800000

ADMIN:
  USER_NAME: ${ADMIN_USERNAME}
  USER_PASSWORD: ${ADMIN_PASSWORD}

MAX_LOGIN_FAILED_ATTEMPTS: 5
LOCK_DURATION: 5
server:
  port: 8081
